# file_transmission.py

import hashlib
import json
import os
from general.message import add_prefix, rstrip_message

CHUNK_SIZE = 1025 
MAX_FILE_SIZE = 104857600 # in bytes; which is equivalent to 100MB
EXT_LIST = ['.txt',  '.md',   '.json', '.xml', '.csv',
           '.docx', '.xlsx', '.pdf',  '.py',  '.html',
           '.css',  '.cpp',  '.java', '.tar.gz',
           '.png',  '.jpg',  '.gif',  '.mp3', '.mp4', '.db']

def display_rule():
    print('\nInput message to send to this chatroom,',
          '\nInput [send] to upload a file to this room,',
          '\nInput [recv] to download a file from this room,',
          '\nInput [msg history] to display all message history in this room,',
          '\nInput [file history] to display all files stored in this room,',
          '\nInput [clear msg history] to delete all message history in this room,'
          '\nInput [clear file history] to delete all files stored in this room,',
          '\nInput [clear all history] to delete all history of this room.',
          '\nInput [ai suggestion] to get message suggestions generated by OpenAI model.',
          '\nPress [Enter/Return] key to disconnect.\n')
    return

def get_file_path(filename, target_dir, start_dir='.'):
    '''
    Used by server to check if it has the file in target_dir,
      for which client wanted to download to their local machine
    '''
    for root, dirs, files in os.walk(start_dir):
        if os.path.basename(root) == target_dir and filename in files:
            return os.path.join(root, filename)
    return None

def check_directory_existence(directory):
    if not directory:
        directory = '.'
    if not os.path.exists(directory):
        print(f'Invalid directory: [{directory}] does not exist.')
        return False
    if not os.access(directory, os.W_OK):
        print(f'Invalid directory: [{directory}] is not writable.')
        return False
    print(f'Directory [{directory}] exists.')
    return True
    
def check_if_file_path_exists(file_path):
    print(f'File path [{file_path}] exists: [{os.path.isfile(file_path)}].')
    return os.path.isfile(file_path)
    
def check_if_file_exists(file_path):
    '''
    Used by the sender to check if the file exists or not.

    @param file_path: the file path of the file
    @return: True if the file path is a file; False otherwise 
    '''
    try:
        if not check_directory_existence(file_path):
            return False
        if not os.path.basename(file_path):
            print('Invalid file path: filename is missing.')
            return False
    except Exception as e:
        print(f'Error validating file path: {e}')
    return check_if_file_path_exists(file_path)

def get_valid_file_path(file_path):    
    while not check_if_file_exists(file_path):
        print('\nType in file path of the file you want to send:')
        print('OR, type <exit> to stop sending file.\n')
        file_path = rstrip_message(input())
        # Client does not want to send the file anymore
        if file_path.lower() == 'exit':
            return None        
    return file_path

def get_extension_from_filename(filename):
    # Returns the extension of a file, including dot.
    # Example: .txt, .pdf, .png, etc..
    return os.path.splitext(filename)[1]

def check_if_file_size_is_valid(file_size, max_file_size):
    def check_valid_file_size(file_size, max_file_size):
        return file_size <= max_file_size
    
    # If file_size is exceeded MAX_FILE_SIZE, stop sending/receiving the file
    if not check_valid_file_size(file_size, max_file_size):
        print(f'Invalid file_size: File has a size of [{file_size}],',
              f'which is larger than Maximum File Size: [{max_file_size}].')
        return False # file_size > MAX_FILE_SIZE
    return True      # file_size <= MAX_FILE_SIZE

def check_if_filename_has_valid_extension(extension, ext_list):
    def check_valid_extension(extension, ext_list):
        return extension in ext_list
    
    # If extension is not in ext_list, stop sending/receiving the file
    if not check_valid_extension(extension, ext_list):
        print(f'Invalid file extension: File ends with [{extension}].',
              f'Valid extensions: {ext_list}.')
        return False # extension not in ext_list
    return True      # extension in ext_list

def compute_hash(data):
    return hashlib.sha256(data).hexdigest()

def read_all_from_file(file_path):
    file_content = b''
    with open(file_path, 'rb') as file:
        file_content = file.read()
    return file_content

def create_metadata(file_path):
    '''
    Used by the sender to create the associate metadata of the file.
    The metadata will be sent to the recipient before receiving 
    the original file.

    @param file_path: the file path of the file
    @return: filename, file_size, hashed_file_content
    '''
    filename = os.path.basename(file_path)
    file_size = os.path.getsize(file_path)
    file_content = read_all_from_file(file_path)
    hashed_file_content = compute_hash(file_content)
    print(f'Filename: [{filename}], file_size: [{file_size}],',
          f'hashed_file_content: [{hashed_file_content}].\n')
    return filename, file_size, hashed_file_content

def send_metadata(socket, filename, file_size, hashed_file_content):
    metadata = {
        'filename': filename,
        'file_size': file_size,
        'hashed_file_content': hashed_file_content
    }
    metadata_json = json.dumps(metadata)
    metadata_bytes = metadata_json.encode()
    socket.send(add_prefix(metadata_bytes, 2))
    return

def send_directory_and_filename(socket, directory, filename):
    dir_and_name = {
        'directory': directory,
        'filename': filename
    }
    dir_and_name_json = json.dumps(dir_and_name)
    dir_and_name_bytes = dir_and_name_json.encode()
    socket.send(add_prefix(dir_and_name_bytes, 3))
    return

def get_directory_and_filename(dir_and_name_encoded):
    dir_and_name_json = dir_and_name_encoded.decode()
    dir_and_name = json.loads(dir_and_name_json)
    directory = dir_and_name['directory']
    filename = dir_and_name['filename']
    print(f'Directory: [{directory}], filename: [{filename}].')
    return directory, filename

def check_metadata_format(metadata):
    if (len(metadata) == 3 and 
        metadata['filename'] and 
        metadata['file_size'] and 
        metadata['hashed_file_content']):
        print('Metadata format is valid.')
        return True
    print('Invalid metadata format.')
    return False

def split_metadata(metadata_bytes):
    metadata_json = metadata_bytes.decode()
    metadata = json.loads(metadata_json)
    filename = metadata['filename']
    file_size = int(metadata['file_size'])
    hashed_file_content = metadata['hashed_file_content']
    print(f'Filename: [{filename}], file_size: [{file_size}],',
          f'hashed_file_content: [{hashed_file_content}].\n')
    return filename, file_size, hashed_file_content

def get_file_path_without_duplication(file_path):
    counter = 1
    filename_with_ext = os.path.basename(file_path)
    filename, extension = os.path.splitext(filename_with_ext)
    base, extension = os.path.splitext(file_path)
    directory = os.path.dirname(file_path)
    while check_if_file_path_exists(file_path):
        # File path exists -> filename is duplicated on recipient's end
        # Need to append a counter to the end of filename, 
        #   but before extension, to solve duplication
        new_filename = f'{filename}_{counter}{extension}'
        file_path = os.path.join(directory, new_filename)
        print(f'New file path: {file_path}')
        counter += 1
    return file_path

def send_file(file_path, filename, socket, chunk_size, recipient):
    '''
    Used by the sender to send the file to the recipient.
    
    @param file_path: the file path of the file
    @param socket: the socket used to send the file; the sender socket
    @param chunk_size: number of bytes to send to the recipient each time
    @param recipient: either 'server' or address of a client; 
                      indicates the receiver side
    @return: None
    '''
    try:
        with open(file_path, 'rb') as file:
            while chunk := file.read(chunk_size):
                socket.send(chunk)
        print(f'Successfully sent file [{filename}] to [{recipient}].')
    except FileNotFoundError:
        print(f'File with path [{file_path}] not found.')
    except Exception as e:
        print(f'Error occurred in send_file(): [{e}].')
    return

def recv_file(filename, file_path, file_size, hashed_file_content, 
             socket, chunk_size, sender):
    '''
    Used by the recipient to receive the file from the sender.
    Received content will be stored in the 'received_files' folder
      with the same filename as the received filename.
    
    @param filename: the string name of the file
    @param file_size: the size of the file
    @param socket: the socket used to receive the file; the receiver socket
    @param chunk_size: number of bytes to receive from the sender each time
    @param sender: either 'server' or address of a client; 
                   indicates the sender side
    @return: None
    '''
    try:
        file_path = os.path.join(file_path, filename)
        file_path = get_file_path_without_duplication(file_path)
        
        # Receive all file content from sender
        data_buffer = b''
        received_len = 0
        while received_len < file_size:
            data = socket.recv(chunk_size)
            if not data:
                break
            data_buffer += data
            received_len += len(data)
            
        # Compute hash of the received content
        recipient_hashed_file_content = compute_hash(data_buffer)
        print(f'Recipient computed hash: [{recipient_hashed_file_content}].')
        print(f'Sender computer hash:    [{hashed_file_content}].')
        
        # Compare the computed result to the one calculated by sender
        if not recipient_hashed_file_content == hashed_file_content:
            print('Error: Recipient hash does not equal to sender hash.')
            print('Stopped receiving file.')
            return False
        
        # Save the file
        with open(file_path, 'wb') as file:
            file.write(data_buffer)

        print('Recipient hash equals to sender hash.')
        print(f'Successfully received file [{filename}] from [{sender}].\n')
        print(f'The file is Stored in file path: [{file_path}].')
        return True
    except Exception as e: 
        print(f'Error occurred in recv_file(): [{e}].')
        return False
