# recv_from_server.py

import pickle 
from client_only.handle_client_actions.handle_msg_suggestion import handle_msg_suggestion
from general.file_transmission import *
from general.message import (get_prefix_and_content, 
                             rstrip_message, 
                             recv_decoded_content)

def handle_recv_request(prefix, type_prefix, msg_content, client, 
                        chunk_size, max_file_size, ext_list):    
    if prefix == 0: 
        # operation message
        print()
    elif prefix == 1: 
        # normal message
        msg_content = rstrip_message(msg_content)
        print(msg_content.decode() + '\n')
    elif prefix == 2: 
        # file-download request initiated by client
        print(f'type prefix: [{type_prefix}]')
        print(f'msg_content: [{msg_content}]')
        
        # file path here should be received from server.
        # Though file path is originally sent from client to server,
        #   since it is sent from the sender thread of the client,
        #   the receiver thread of the client (this thread) does not know file path.
        # Thus, this thread needs the server to relay file path to it.
        file_path = rstrip_message(msg_content).decode()
        print(f'file path: [{file_path}]')
        recv_file_from_server(client, file_path, chunk_size, max_file_size, ext_list)
    elif prefix == 3:
        # file-upload request initiated by client
        # handled in handle_send_file_request.py
        print('file-upload request initiated by client.')
    elif prefix == 4: 
        # display msg/file history request
        response = pickle.loads(msg_content)
        if type(response) == str and response == 'INVALID':
            print('Response from server: Invalid display history request.\n')
        else:    
            print(response, '\n')
    elif prefix == 5: 
        # clear msg/file/all history request
        response = msg_content.decode()
        print(response+'\n')
    elif prefix == 6: 
        # message suggestions generated by OpenAI model
        handle_msg_suggestion(client, msg_content)
    else: # invalid prefix
        print(f'Received invalid prefix: [{type_prefix}].')
    return

def recv_msg_from_server(client, shutdown_event, chunk_size, 
                         max_file_size, ext_list):
    # Receive message from server
    while not shutdown_event.is_set(): 
        try:
            msg = client.recv(chunk_size) # 1025 bytes
            
            # Empty message received -> server closed connection
            if not msg:
                print('Server has closed the connection.')
                shutdown_event.set()
                break 
            
            if msg == (b'\x03\x02\x01\x00HEART'):
                print('Server has sent a HEARTBEAT message with header: \x03\x02\x01\x00HEART.')
                continue
            
            type_prefix, msg_content = get_prefix_and_content(msg)
            prefix = int.from_bytes(type_prefix, byteorder='big')
            
            print(f'type_prefix: {type_prefix}')
            print(f'prefix: {prefix}')
            print(f'msg_content: {msg_content}')

            handle_recv_request(prefix, type_prefix, msg_content, client, 
                                chunk_size, max_file_size, ext_list)
        except Exception as e:
            print(f'Error [{e}] occurred when receiving message.')
            break 
    client.close() # will be detected by server's 'recv()'
    print('Client receiver thread stopped.')
    return

def recv_file_from_server(client, file_path, chunk_size, max_file_size, ext_list):
    # Receive server response for whether server has that file or not
    # If server has it, response should be 'file_exists'
    # Otherwise, response should be 'file_not_found'
    response = recv_decoded_content(client, chunk_size)
    print(f'Received response on file-download from server: {response}')
    if response == 'file_exists':
        # Receive metadata from server
        msg = client.recv(chunk_size)
        prefix, metadata_bytes = get_prefix_and_content(msg)
        filename, file_size, hashed_file_content = split_metadata(metadata_bytes)
        
        # Stop receiving file if file_size is greater than MAX_FILE_SIZE
        if not check_if_file_size_is_valid(file_size, max_file_size):
            print('Stopped receiving file.')
            display_rule()
            return 
        
        # Stop receiving file if file extension is not in ext_list
        extension = get_extension_from_filename(filename)
        if not check_if_filename_has_valid_extension(extension, ext_list):
            print('Stopped receiving file.')
            display_rule()
            return 
        
        # Receive file from server, and store it on client desired location
        recv_file(filename, file_path, file_size, hashed_file_content, 
                  client, chunk_size, 'server')
        
        display_rule()
    elif response == 'file_not_found':
        print('Stopped receiving file.')
        display_rule()
    else:
        print(f'Received invalid response from server: [{response}]',
              f'when receiving file.')
    return
