# handle_request.py

from server_only.handle_requests.handle_clear_history_request import handle_clear_history_request
from server_only.handle_requests.handle_display_history_request import handle_display_history_request
from server_only.handle_requests.handle_download_request import handle_download_request
from server_only.handle_requests.handle_msg_suggestion_request import handle_msg_suggestion_request
from server_only.handle_requests.handle_normal_msg import handle_normal_msg
from server_only.handle_requests.handle_upload_request import handle_upload_request

def handle_request(prefix, client, username, msg_content, clients, 
                   room, room_code, address, chunk_size, max_file_size, 
                   ext_list, type_prefix, using_open_ai):
    if prefix == 0:
        # Received operation message
        print('Received operation message.')
        print(f'msg_content:{msg_content}\n')
    elif prefix == 1: 
        # Received normal message
        handle_normal_msg(client, address, username, msg_content, clients, room)
    elif prefix == 2: 
        # Received file-upload request
        handle_upload_request(client, address, room, room_code,
                                chunk_size, max_file_size, ext_list)
    elif prefix == 3: 
        # Received file-download request
        handle_download_request(client, address, room, room_code,
                                msg_content, chunk_size, 
                                max_file_size, ext_list)
    elif prefix == 4: 
        # Received display msg/file history request
        handle_display_history_request(client, address, msg_content, room)
    elif prefix == 5: 
        # Received clear msg/file/all history request
        handle_clear_history_request(client, address, msg_content, room)
    elif prefix == 6: 
        # Received message suggestions generated by OpenAI model request
        handle_msg_suggestion_request(client, room.get_message_list(), using_open_ai)
    else: 
        # Received invalid prefix
        print(f'Received invalid prefix: {type_prefix}.')
    return
