# client_onboarding.py

from client_only.client_core.client_sender_thread_ops import (send_decision_on_room, 
                                                              send_room_code,
                                                              send_username)

def handle_room_decision(client, chunkSize):
    # Try sending client decision on room to server
    # If msg is 'C', response will be a room code generated by server
    # If msg is 'E', response will be:
    #   1. server generated room code, if received <c> from client
    #   2. 'VALID_ROOM_CODE' sent by server, if the room code is valid
    #   3. an error message sent by server, otherwise
    # Otherwise,     response will be an error message sent by server
    print('Input <C> to Create a new room, OR')
    print('Input <E> to Enter an existing room.\n')
    msg, response = send_decision_on_room(client, chunkSize)
    while msg.upper() != 'C':
        print(f'msg: [{msg}], response from server: [{response}]')
        if msg.upper() == 'E':
            msg, response = send_room_code(client, chunkSize)
            print(f'msg: [{msg}], response from server: [{response}]')
            if msg.upper() == 'C':
                break
            if response == 'VALID_ROOM_CODE':
                response = msg
                break
        msg, response = send_decision_on_room(client, chunkSize)
    print(f'In Room: [{response}].\n')
    return

def handle_username(client, chunkSize):
# Try sending client username to server
    msg, response = send_username(client, chunkSize)
    while response != 'VALID_USERNAME':
        print(f'msg: [{msg}], response from server: [{response}]')
        msg, response = send_username(client, chunkSize)
    return
        