# mongodb_initiator.py

import gridfs
from pymongo import MongoClient

# Connect to MongoDB with the connection string for Giraffael2DB
uri = ('mongodb+srv://jianminglin2893:cbVSqJdDMIUnso6Q' + 
       '@ac-os3juge.wu2ivo7.mongodb.net/Giraffael2DB' + 
       '?retryWrites=true&w=majority&tls=true')
mongoClient = MongoClient(uri, serverSelectionTimeoutMS=3000)
db = mongoClient['Giraffael2DB']
rooms_collection = db['Rooms']
user_profiles_collection = db['UserProfiles']
user_statuses_collection = db['UserStatuses']
gfs = gridfs.GridFS(db)


'''
Database: 

- Collection 1 (The “Rooms” collection). 
    Each Room in rooms_collection has the following attributes:
    - roomCode
    - roomName
    - clientList
        - each entry is a dict returned by Client_Obj.to_dict().
    - msgList
        - each entry is a dict containing the metadata of the msg, 
            i.e. senderID (uuid), senderName (username), and the message.
    - fileList
        - each entry is a dict containing fileID (generated by gfs.put()) and filename.
- Collection 2 (The “UserProfiles” Collection). 
    Each User in user_profiles_collection has the following attributes:
    - uuid
    - address
    - username
    - Note: the “socket” field of client_obj was not included as it cannot be added to MongoDB collection.
- Collection 3 (The “UserStatuses” Collection). 
    Each User in user_statuses_collection has the following attributes:
    - uuid
    - last_activity_timestamp
    - online_status
'''
