# mongodb_initiator.py

import gridfs
from pymongo import MongoClient

# Connect to MongoDB with the connection string for Giraffael2DB
uri = ('mongodb+srv://jianminglin2893:cbVSqJdDMIUnso6Q' + 
       '@ac-os3juge.wu2ivo7.mongodb.net/Giraffael2DB' + 
       '?retryWrites=true&w=majority&tls=true')
mongoClient = MongoClient(uri, serverSelectionTimeoutMS=3000)
db = mongoClient['Giraffael2DB']
rooms_collection = db['Rooms']
user_profiles_collection = db['UserProfiles']
gfs = gridfs.GridFS(db)


'''
Database: 
- Collection 1 (The “Rooms” collection). 
    Each Room in rooms_collection has the following attributes:
    - room_code
    - room_name
    - client_list
        - each entry is a dict containing a uuid and an username
    - msg_list
        - each entry is a dict containing the metadata of the msg, 
            i.e. senderID (uuid), senderName (username), and the message.
    - file_list
        - each entry is a dict containing fileID (generated by gfs.put()) and filename.
    - creation_date
- Collection 2 (The “UserProfiles” Collection). 
    Each User in user_profiles_collection has the following attributes:
    - uuid
    - username
    - and more!
'''
